import React from "react";
import TradingMap from "./trading-map";
import TradingTable from "./trading-table";

const mockData = [
  {
    id: "China",
    country: "China",
    area: "Asia",
    proportion: "68.23",
    shipments: "280430",
    weight: "31442",
    teu: "24",
  },
  {
    id: "India",
    country: "India",
    area: "Asia",
    proportion: "15.12",
    shipments: "62154",
    weight: "29502",
    teu: "16",
  },
  {
    id: "Bangladesh",
    country: "Bangladesh",
    area: "Asia",
    proportion: "2.34",
    shipments: "17549",
    weight: "12442",
    teu: "14",
  },
  {
    id: "Pakistan",
    country: "Pakistan",
    area: "Asia",
    proportion: "8.23",
    shipments: "10614",
    weight: "76743",
    teu: "12",
  },
  {
    id: "Cambodia",
    country: "Cambodia",
    area: "Asia",
    proportion: "20.34",
    shipments: "8051",
    weight: "12059",
    teu: "4",
  },
  {
    id: "Norway",
    country: "Norway",
    area: "Europe",
    proportion: "20.34",
    shipments: "7632",
    weight: "53005",
    teu: "14",
  },
  {
    id: "Romania",
    country: "Romania",
    area: "Europe",
    proportion: "2.34",
    shipments: "2290",
    weight: "2134",
    teu: "34",
  },
  {
    id: "Italia",
    country: "Italia",
    area: "Europe",
    proportion: "10.34",
    shipments: "1692",
    weight: "23005",
    teu: "18",
  },
  {
    id: "Croatia",
    country: "Croatia",
    area: "Europe",
    proportion: "20.34",
    shipments: "696",
    weight: "3005",
    teu: "8",
  },
  {
    id: "Hungary",
    country: "Hungary",
    area: "Europe",
    proportion: "12.30",
    shipments: "513",
    weight: "1400",
    teu: "4",
  },
  {
    id: "Chile",
    country: "Chile",
    area: "South America",
    proportion: "22.30",
    shipments: "7545",
    weight: "17000",
    teu: "34",
  },
  {
    id: "Peru",
    country: "Peru",
    area: "South America",
    proportion: "2.30",
    shipments: "1689",
    weight: "7000",
    teu: "16",
  },
  {
    id: "Columbia",
    country: "Columbia",
    area: "South America",
    proportion: "22.30",
    shipments: "1401",
    weight: "13000",
    teu: "24",
  },
  {
    id: "Ecuador",
    country: "Ecuador",
    area: "South America",
    proportion: "12.30",
    shipments: "663",
    weight: "1000",
    teu: "1",
  },
  {
    id: "Brazil",
    country: "Brazil",
    area: "South America",
    proportion: "13.20",
    shipments: "433",
    weight: "20000",
    teu: "5",
  },
  {
    id: "Guatemala",
    country: "Guatemala",
    area: "North America",
    proportion: "53.20",
    shipments: "2155",
    weight: "40000",
    teu: "30",
  },
  {
    id: "Honduras",
    country: "Honduras",
    area: "North America",
    proportion: "53.20",
    shipments: "1910",
    weight: "25000",
    teu: "20",
  },
  {
    id: "Dominican Republic",
    country: "Dominican Republic",
    area: "North America",
    proportion: "13.20",
    shipments: "1866",
    weight: "32341",
    teu: "40",
  },
  {
    id: "Nicaragua",
    country: "Nicaragua",
    area: "North America",
    proportion: "33.20",
    shipments: "1089",
    weight: "3000",
    teu: "3",
  },
  {
    id: "Haiti",
    country: "Haiti",
    area: "North America",
    proportion: "3.20",
    shipments: "756",
    weight: "4000",
    teu: "7",
  },
  {
    id: "Nigeria",
    country: "Nigeria",
    area: "Africa",
    proportion: "3.20",
    shipments: "1863",
    weight: "3200",
    teu: "20",
  },
  {
    id: "Lesotho",
    country: "Lesotho",
    area: "Africa",
    proportion: "23.20",
    shipments: "812",
    weight: "320",
    teu: "2",
  },
  {
    id: "South Africa",
    country: "South Africa",
    area: "Africa",
    proportion: "3.20",
    shipments: "766",
    weight: "7200",
    teu: "30",
  },
  {
    id: "Morocco",
    country: "Morocco",
    area: "Africa",
    proportion: "3.20",
    shipments: "146",
    weight: "320",
    teu: "5",
  },
  {
    id: "Nambia",
    country: "Nambia",
    area: "Africa",
    proportion: "3.20",
    shipments: "88",
    weight: "200",
    teu: "1",
  },
];

const Home = () => {
  return (
    <div className="min-w-[100vw] min-h-screen flex flex-col gap-4 items-center bg-gray-100 p-8">
      <TradingMap data={mockData} />
      <TradingTable data={mockData} />
    </div>
  );
};

export default Home;
